# Generated by Django 4.2.5 on 2023-09-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reserva", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="localizacao",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="reserva.stand",
            ),
            preserve_default=False,
        ),
    ]
