# Generated by Django 4.2.5 on 2023-09-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reserva", "0002_reserva_localizacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="localizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_localizacao",
                to="reserva.stand",
            ),
        ),
    ]
