# Generated by Django 4.2.6 on 2023-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_alter_reserva_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor'),
        ),
    ]
